# Site settings
title: "|kiloʊˈdɛltə|"
email: will@kilodelta.com
url: https://kd8drx.github.io
description: "Hi. I'm Will. I live in Seattle. Let's talk."

# Site content stuff
header: Hello.
byline: I'm Will. I live in Seattle. Let's talk.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ffffff'

# Footer settings
footer: Will Green

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    display: twitter
    url: https://twitter.com/kilodelta
  - title: facebook
    display: facebook
    url: https://facebook.com/kilodelta
  - title: tumblr
    display: tumblr
    url: http://kilodelta.tumblr.com
  - title: linkedin
    display: linkedin
    url: http://linkedin.com/in/kilodelta
  - title: github
    display: github
    url: https://github.com/kd8drx
  - title: envelope
    display: email
    url: mailto:will@kilodelta.com
  - title: skype
    display: skype
    url: skype:compboy1

# Build settings
markdown: kramdown
permalink: pretty
